# Generated by Django 4.1.3 on 2022-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField(blank=True, max_length=200, null=True)),
                ("mobile", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=50)),
                (
                    "pic",
                    models.FileField(default="sad.jpg", upload_to="seller_profile"),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(max_length=20)),
            ],
        ),
    ]
